server:
  port: 8081
  servlet:
    context-path: /v1
spring:
  application:
    name: api-starwars-application
  data:
    mongodb:
      database: starwars
      host: localhost
  profiles:
    active: local
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    operationsSorter: method
    path: /swagger
swapi:
  url: https://swapi.dev/api/planets/